### PR TITLE
Check if a variable has more than two levels

### PR DESCRIPTION
**Pull request by Kucharssim**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1832

### CODE REVIEW

**Comment by boutinb** [comment]
@vandenman , @Kucharssim Should we merge this?

**Comment by vandenman** [comment]
err... isn't this by design? I'm not sure if this is really a bug. Sure it's funny that you can do a binomial test with variables with more than 2 levels but the analysis does do the right thing in the sense that it tests each level individually. A similar issue might be that the independent samples t-test allows for multiple variables, even though a t-test really only concerns one variable and a grouping variable.

**Comment by vandenman** [comment]
The code was also definitely written with the idea that variables could have more than two levels.

**Comment by Kucharssim** [comment]
Well, that's what I thought as well at first, but there are some issues with this:

1. The help files quite specifically spell out that you have to use binary variables in the analysis. 
2. How useful this is if we consider it a "feature"? I fail to come up with a good use case. If you have more than two categories, just do a multinomial test instead of several independent binomial tests, no? 
3. Regarding your example with the t-test, the binomial analysis also allows using multiple dependent variables, so that feature is still preserved. This is more akin to if you used a grouping variable with more than two levels in an independent samples t-test, you would get results of every pairwise comparison instead of getting a "Grouping variable must have exactly two levels" error message.

**Comment by vandenman** [comment]
Hmmm, fair point. @EJWagenmakers any objections?

**Comment by Kucharssim** [comment]
Closing this PR since the current behavior is desired as pointed out by @EJWagenmakers:

> Yes, we should keep it as is.
For instance, suppose I have three levels:
(a) loves cats; (b) loves small dogs; (c) loves big dogs
>Now I might want to test (a) against everything else. 

I'll make an alternative PR that clarifies this in the help file

**Pull request closed without merging**
