### PR TITLE
Fix problem with tables not being removed

### PR DESCRIPTION
**Pull request by TimKDJ**
Fixes https://github.com/jasp-stats/jasp-issues/issues/908

The problem was that the names of the container in the state were indexed by number. 
So if we had tableA and tableB in the slots state_1->tableA, state_2->tableB and the tableA was removed, then we'd have state[2]->tableB still but also add an additional state[1]->tableB

I couldn't test it as thoroughly as I'd liked because the dynamic module install crashes my JASP.

### CODE REVIEW

**Comment by TimKDJ** [comment]
Actually I noticed more number based indices so I need to look a bit further.

**Comment by TimKDJ** [comment]
I've also fixed the number based indexing for the log odds plot, which caused the plots to never be retrieved from the state.
There was also a bug that if you enter multiple rows and one had > 2 levels, then not a single log odds ratio plot would be created.

Could you have a look @Kucharssim?

**Comment by Kucharssim** [comment]
Yes I will

**Review by Kucharssim — APPROVED** [review]
lgtm!

**Pull request merged**
